export const CHANGE_INPUT = "CHANGE_INPUT";
export const SAVE_MATCHED_STATIONS = "SAVE_MATCHED_STATIONS";
export const TOGGLE_SHOW_MATCHED_STATIONS = "TOGGLE_SHOW_MATCHED_STATIONS";

export const SAVE_AQI_DATA = "SAVE_AQI_DATA";
export const TOGGLE_IS_LOADING_AQI = "TOGGLE_IS_LOADING_AQI";
export const TOGGLE_HAS_ERROR = "TOGGLE_HAS_ERROR";
